linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - golint
    - gocritic
    - stylecheck
    - goimports
    - gosec
    - unconvert
    - maligned
    - prealloc
    - gochecknoglobals

service:
  golangci-lint-version: 1.21.x

issues:
  exclude-rules:
    - text: "receiver name should be a reflection of its identity; don't use generic names such as \"this\" or \"self\""
      linters:
        - golint
