name: Build

on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod

    - run: make build
